Models/Advertisement.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Projet_5.Models
{
    /// <summary>
    /// Advertisement est l'entité qui représente les annonces des véhiculesn, on y retrouve ses propriétés et ses relations.
    /// </summary>
    public class Advertisement
    {
        /// <summary>
        /// Identifiant unique de l'annonce généré automatiquement par la base de données.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Date de la mise en vente du véhicule.
        /// </summary>
        public DateTime DisponibilityDate { get; set; }

        /// <summary>
        /// Indique si le véhicule est disponible à la vente.
        /// True étant un véhicule disponible.
        /// False étant un véhicule non disponible.
        /// </summary>
        public bool Disponibility { get; set; }

        /// <summary>
        /// Indique si le véhicule a été vendu.
        /// True étant un véhicule vendu.
        /// False étant un véhicule invendu.
        /// </summary>
        public bool Selled { get; set; }

        /// <summary>
        /// Description du véhicule visible dans l'annonce.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Chemin de la photo du véhicule.
        /// </summary>
        public string? PhotoPath { get; set; }


        /// <summary>
        /// Identifiant unique du véhicule associé à l'annonce.
        /// </summary>
        public int VehicleId { get; set; }

        /// <summary>
        /// Instance de l'objet Vehicle(Vehicule) associé à l'annonce contenant les détails du vehicule.
        /// </summary>
        public Vehicle Vehicle { get; set; }

        /// <summary>
        /// Liste des objets Transaction associée à l'annonce contenant les détails des transactions.
        /// </summary>
        public ICollection<Transaction> Transaction { get; set; }

    }
}

Controllers/AdvertisementController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Projet_5.Models;
using Projet_5.Services;

namespace Projet_5.Controllers
{
    /// <summary>
    /// Controleur pour gérer les opérations liées aux annonces, tel que la création, la mise à jour, la recherche et la suppression des annonces.
    /// </summary>
    [Route("api/[controller]")]
    [ApiController]
    public class AdvertisementController : Controller
    {
        private readonly IAdvertisementService _advertisementService;
        private readonly IVehicleService _vehicleService;
        private readonly IRepairService _repairService;
        private readonly ITransactionService _transactionService;

        /// <summary>
        /// Constructeur injectant les dépendances pour gérer les annonces, véhicules, réparation et transaction.
        /// </summary>
        /// <param name="advertisementService"> Service pour gérer les opérations liées aux annonces.</param>
        /// <param name="vehicleService"> Service pour gérer les opérations liées aux véhicules.</param>
        /// <param name="repairService"> Service pour gérer les réparations liées aux réparations.</param>
        /// <param name="transactionService"> Service pour gérer les transactions liées aux transactions.</param>
        public AdvertisementController(IAdvertisementService advertisementService,IVehicleService vehicleService, IRepairService repairService, ITransactionService transactionService)
        {
            _advertisementService = advertisementService;
            _vehicleService = vehicleService;
            _repairService = repairService;
            _transactionService = transactionService;

        }

        /// <summary>
        /// Récupère toutes les annonces enregistrées dans la base de données.
        /// </summary>
        /// <returns> Retourne un objet JSON contenant la liste des annonces enregistrées avec le statut code HTTP200</returns>
        [HttpGet]
        public async Task<IActionResult> GetAllAdvertisements()
        {
            var advertisements = await _advertisementService.GetAllAdvertisementsAsync();
            return Ok(advertisements);
        }

        /// <summary>
        /// Récupère une annonce dont l'Id correspond à l'Id recherché. 
        /// </summary>
        /// <param name="id"> Id de l'annonce a recherché.</param>
        /// <returns>Retourne un objet JSON contenant les informations de l'annonce correspondante avec le statut code HTTP200
        /// Si l'annonce correspondant à l'Id n'existe pas, retourne une réponse HTTP404(NotFound)
        /// </returns>
        [HttpGet("{id}")]
        public async Task<IActionResult> GetAdvertisementById(int id)
        {
            var advertisement = await _advertisementService.GetAdvertisementByIdAsync(id);
            if (advertisement == null)
            {
                return NotFound();
            }
            return Ok(advertisement);
        }

        /// <summary>
        /// Met à jour les informations d'une annonce existante.
        /// </summary>
        /// <param name="id"> Id de l'annonce a mettre à jour.</param>
        /// <param name="updatedAdvertisement"> Le modèle de l'annonce contenant les informations pour mettre à jour l'annonce..</param>
        /// <returns> Retourne un status code HTTP 400(Bad Request) si les informations du modèles sont invalides.
        /// Retourne un status code HTTP 404 (Not Found) si l'annonce n'est pas trouvée.
        /// Retourne un status code HTTP 204 (NoContent) si la mise à jour a été effectué.
        /// </returns>
        [HttpPut("{id}")]
        public async Task<IActionResult> UpdateAdvertisement(int id, [FromBody] Advertisement updatedAdvertisement)
        {
            if (id != updatedAdvertisement.Id)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var success = await _advertisementService.UpdateAdvertisementAsync(updatedAdvertisement);
            if (!success)
            {
                return NotFound();
            }

            return NoContent();
        }

        /// <summary>
        /// Supprime une annonce existante
        /// </summary>
        /// <param name="id"> Id de l'annonce à supprimer.</param>
        /// <returns> Retourne un status code HTTP 404 (Not Found) si le annonce n'est pas trouvée.
        /// Retourne un status code HTTP 204 (NoContent) si la mise à jour a été effectué.
        /// </returns>
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteAdvertisement(int id)
        {
            var success = await _advertisementService.DeleteAdvertisementAsync(id);
            if (!success)
            {
                return NotFound();
            }

            return NoContent();
        }

        /// <summary>
        /// Modifie l'état de la disponibilité du véhicule.
        /// </summary>
        /// <param name="vehicleId"> Id du véhicle dont il faut mettre à jour la disponibilité</param>
        /// <param name="disponibility"> Etat de la disponiblité du véhicule.</param>
        /// <returns> Redirige vers la vue de détails du véhicule.</returns>
        [HttpPost]
        [Route("SetDisponibility")]
        public async Task<IActionResult> SetDisponibility([FromForm] int vehicleId, [FromForm] bool disponibility)
        {
            try
            {
                await _advertisementService.SetDisponibilityAsync(vehicleId, disponibility);
                return RedirectToAction("Details", new { id = vehicleId });
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Details", "Details", new { id = vehicleId });
            }
        }

        /// <summary>
        /// Met à jour la déscription de l'annonce.
        /// </summary>
        /// <param name="id"> Id de l'annonce dont il faut mettre à jour la déscription.</param>
        /// <param name="description"> Le modèle de vue contenant la déscription pour mettre à jour l'annonce.</param>
        /// <returns> Retourne un objet JSON avec le statut code 200 et les informations de la déscription.</returns>
        [HttpPut("{id}")]
        public async Task<IActionResult> UpdateDescription(int id, [FromBody] string description)
        {
            if (string.IsNullOrWhiteSpace(description))
            {
                return BadRequest();
            }

            var success = await _advertisementService.UpdateDescriptionAsync(id, description);
            if (!success)
            {
                return NotFound();
            }

            return Ok();
        }

        /// <summary>
        /// Affiche les détails d'un véhicule, y compris les réparations, les transactions associés et le prix de vente calculé.
        /// </summary>
        /// <param name="id"> Id du véhicule dont on veut afficher les annonces.</param>
        /// <returns> Retourne la vue contentant les détails du véhicule.
        /// Retourne une erreur 404(NotFound) si l'identifiant ne correspond pas à un véhicule existant.
        /// </returns>
        [HttpGet("Details")]
        public async Task<IActionResult> Details(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }

            var vehicle = await _vehicleService.GetVehicleByIdAsync(id);

            if (vehicle == null)
            {
                return NotFound();
            }

            var repair = await _repairService.GetRepairsByVehicleIdAsync(id);
            var buyingTransaction = await _transactionService.GetBuyingTransactionByVehicleIdAsync(id);
            var sellingPrice = await _advertisementService.CalculateSellingPriceAsync(id);
            var advertisement = await _advertisementService.GetAdvertisementByVehicleIdAsync(id);

            var model = new VehicleDetailsViewModel
            {
                Vehicle = vehicle,
                Repairs = repair,
                BuyingTransaction = buyingTransaction,
                SellingPrice = sellingPrice,
                Advertisement = advertisement
            };

            return View(model);
        }

        /// <summary>
        /// Modifie l'état de vente du véhicule.
        /// </summary>
        /// <param name="vehicleId"> Id du véhicule dont on veut modifier l'état de vente.</param>
        /// <param name="selled"> Boolen qui indique l'état de vente du véhicule.
        /// True étant un véhicule vendu.
        /// False étant un véhicule non vendu. </param>
        /// <returns> Redirige vers la vue de détails du véhicule.</returns>
        [HttpPost]
        [Route("SetSelled")]
        public async Task<IActionResult> SetSelled([FromForm] int vehicleId, [FromForm] bool selled)
        {
            try
            {
                await _advertisementService.SetSelledAsync(vehicleId, selled);
                return RedirectToAction("Details", new { id = vehicleId });
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Details", "Details", new { id = vehicleId });
            }
        }

        /// <summary>
        /// Calcule le prix de vente en faisant la somme du prix d'achat du véhicule, du cout des réparations et de la marge initiale de 500€.
        /// </summary>
        /// <param name="vehicleId"> Id du véhicule dont il faut recalculer le prix de vente.</param>
        /// <param name="advertisementId"> Id de l'annonce dont il faut mettre à jour le prix de vente.</param>
        /// <returns> Redirige vers la vue de détails du véhicule.</returns>
        [HttpPost]
        [Route("CalculateSellingPrice")]
        public async Task<IActionResult> CalculateSellingPrice(int vehicleId, int advertisementId)
        {

Views/Advertisement/Details.cshtml
@model VehicleDetailsViewModel

@{
    ViewData["Title"] = "Détails du véhicule";
}

<h2>@ViewData["Title"]</h2>

<div>
    
    <div style="display: flex; gap: 20px; align-items: flex-start;">
        <div style="flex: 1;">
            @if (!string.IsNullOrEmpty(Model.Vehicle.PhotoPath))
            {
                <div>
                <img src="@Model.Vehicle.PhotoPath"
                         alt="@($"{Model.Vehicle.Brand} {Model.Vehicle.Model} - Image de présentation")"
                style="max-width: 100%; height: auto;" />
                </div>
            }
        </div>

        <div style="flex: 2;">
            @if(Model.Advertisement.Disponibility == true || User.IsInRole("Admin"))
            {
            @if (Model.SellingPrice != null)
            {
                <h3>Prix de vente: @Model.SellingPrice € </h3>
            }
            }
            
            @if (User.IsInRole("Admin"))
            {
                <p><strong>VIN:</strong> @Model.Vehicle.VIN</p>
            }

            <p><strong>Année:</strong> @Model.Vehicle.Year</p>
            <p><strong>Marque:</strong> @Model.Vehicle.Brand</p>
            <p><strong>Modèle:</strong> @Model.Vehicle.Model</p>
            <p><strong>Finition:</strong> @Model.Vehicle.Finition</p>
            

            @if (User.IsInRole("Admin"))
            {
                @if (Model.BuyingTransaction != null)
                {
                    <h4>Prix d'achat</h4>
                    <p><strong>Montant:</strong> @Model.BuyingTransaction.Amount €</p>
                    <p><strong>Date de la transaction:</strong> @Model.BuyingTransaction.TransactionDate.ToShortDateString()</p>
                }
            }
        </div>
    </div>
            @if (User.IsInRole("Admin"))
            {
                @if (Model.Repairs.Any())
                {
                    <h4>Réparations effectuées</h4>
                    <table class="repair">
                        @foreach (var repair in Model.Repairs)
                        {
                            <tr>
                        <td>@repair.Reparation - @repair.Cost €</td>
                                <td><a href="@Url.Action("EditRepair", "Repair", new { id = repair.Id })" class="btn btn-primary btn-sm">Modifier</a>
                                <form asp-action="DeleteRepair" asp-controller="Repair" method="post" style="display:inline;">
                                    <input type="hidden" name="repairId" value="@repair.Id" />
                                    <button type="submit" class="btn btn-danger btn-sm">Supprimer</button>
                            </form>
                        </td>
                            </tr>
                        }
                    </table>
                }

        <h4>Disponibilité</h4>
        <form asp-action="SetDisponibility" asp-controller="Advertisement" method="post">
            <input type="hidden" name="vehicleId" value="@Model.Vehicle.Id" />
            <label>
                <strong>Disponible à la vente :</strong>
                <input
                    type="checkbox"
                    name="disponibility"
                    value="true" @(Model.Advertisement.Disponibility == true ? "checked" : "")
                    onchange="this.form.submit();" />
            </label>
        </form>
        @if (Model.Advertisement?.Disponibility == true)
        {
            <p>
                <strong>Date de disponibilité :</strong>
                @(Model.Advertisement?.DisponibilityDate.ToShortDateString() ?? "N/A")
            </p>
        
            <h4>Vente</h4>
            <form asp-action="SetSelled" asp-controller="Advertisement" method="post">
                <input type="hidden" name="vehicleId" value="@Model.Vehicle.Id" />
                <label>
                    <strong>Vehicule vendu :</strong>
                    <input type="checkbox"
                           name="selled"
                           value="true" @(Model.Advertisement.Selled == true ? "checked" : "")
                           onchange="this.form.submit();" />
                </label>
            </form>
        }
        <div>
            <a href="@Url.Action("EditCar", "Vehicle", new { id = Model.Vehicle.Id })" class="btn btn-primary">Modifier le véhicule</a>
            <a href="@Url.Action("AddRepair", "Repair", new { vehicleId = Model.Vehicle.Id })" class="btn btn-secondary">Ajouter une réparation</a>
        </div>
        <form asp-controller="Vehicle" asp-action="DeleteVehicle" method="post">
            <input type="hidden" name="id" value="@Model.Vehicle.Id" />
            <button type="submit" class="btn btn-danger">Supprimer le véhicule</button>
        </form>
        }

    <a href="@Url.Action("Index", "Home")" class="btn btn-secondary">Retour à l'accueil</a>
</div>